version: '3.3'
services:
  animalia:
    build: .
    ports:
      - 13337:8080
      - 13338:8081
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    env_file:
      - .env
